# Generated by Django 4.2.7 on 2023-11-15 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0018_auto_20211028_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimos",
            name="data_emprestimo",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 15, 19, 23, 22, 701006)
            ),
        ),
    ]
